import type { Metadata } from "next";
import { Bebas_Neue, Lato, Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Providers from "@/components/Providers";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas-neue",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Abe Garage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="/images/imgi_3_favicon.png" type="image/png" />
        <link
          rel="shortcut icon"
          href="/images/imgi_3_favicon.png"
          type="image/png"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/fonts/flaticon.css"
        ></link>
      </head>
      <body
        className={`${bebasNeue.variable} ${lato.variable} ${jost.variable} font-sans`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
          <ScrollToTopButton />
        </Providers>
      </body>
    </html>
  );
}
